import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'MLBB Analyst',
      'recent': 'Games',
      'stats': 'Stats',
      'search': 'Search',
      'add': 'Add',
      'settings': 'Settings',
      'victory': 'VICTORY',
      'defeat': 'DEFEAT',
      'my_team': 'MY TEAM',
      'enemy_team': 'ENEMY TEAM',
      'with_me': 'WITH ME',
      'against_me': 'AGAINST ME',
      'without_me': 'WITHOUT ME',
      'standalone': 'Standalone',
      'hero': 'Hero',
      'nickname': 'Nickname',
      'kda': 'KDA',
      'gold': 'Gold',
      'items': 'Items',
      'score': 'Score',
      'duration': 'Duration',
      'match_date': 'Match Date',
      'match_time': 'Match Time',
      'save_match': 'SAVE MATCH',
      'scan_screenshot': 'SCAN SCREENSHOT',
      'cancel': 'Cancel',
      'save': 'Save',
      'required': 'Required',
      'invalid': 'Invalid',
      'match_details': 'Match Details',
      'no_games': 'No games recorded yet.',
      'delete_game': 'Game deleted',
      'language': 'Language',
      'theme': 'Theme',
      'developer_mode': 'Developer Mode',
      'about': 'About',
      'error': 'Error',
      'ok': 'OK',
      'search_hint': 'Search by Player or Hero',
      'role': 'Role',
      'jungle': 'Jungle',
      'roam': 'Roam',
      'mid': 'Mid Lane',
      'gold_lane': 'Gold Lane',
      'exp_lane': 'Exp Lane',
      'unknown': 'Unknown',
      'select_blessing': 'Select Blessing',
      'none_boots': 'None (Normal Boots)',
      'physical': 'Physical',
      'magic': 'Magic',
      'defense': 'Defense',
      'movement': 'Movement',
      'all': 'All',
      'tier_3': 'Tier 3',
      'tier_all': 'All Tiers',
      'spell': 'Spell',
      'select_spell': 'Select Spell',
      'my_nickname': 'My Nickname',
      'manage_players': 'Players',
      'players_desc': 'Manage nicknames and comments',
      'level': 'Level',
      'battle_stats': 'BATTLE STATS',
      'damage_hero': 'Damage to Heroes',
      'damage_tower': 'Damage to Towers',
      'damage_taken': 'Damage Taken',
      'heal_label': 'Healing',
      'kill_part': 'Kill Participation',
      'cc_label': 'Control',
      'best_streak': 'Best Streak',
      'gold_sources': 'GOLD SOURCES',
      'lane_gold': 'Lane',
      'kill_gold': 'Kills',
      'jungle_gold': 'Jungle',
      'close': 'CLOSE',
      'alias': 'Aliases (Nicknames)',
      'comments': 'Comments',
      'add_alias': 'Add new alias',
      'add_comment_hint': 'Add comment',
      'unpin': 'Unpin',
      'pin_desc': 'Pin (will be main)',
      'history': 'GAME HISTORY',
      'top_heroes': 'TOP HEROES',
      'other_heroes': 'OTHER HEROES',
      'games_count': 'Games:',
      'ally': 'Ally',
      'enemy': 'Enemy',
      'player_profile': 'Player Profile',
      'your_profile': 'Your Profile',
      'player_settings': 'Player Settings',
      'search_stats_coming': 'Statistics Coming Soon',
      'search_coming': 'Search Coming Soon',
      'search_stats_desc': 'Win rates, favorite heroes, and more!',
      'search_desc': 'Search by player, hero, or match ID!',
      'empty': 'Empty',
      'you_label': 'It\'s you',
      'search_nick_hint': 'Search by nickname...',
      'save_id_success': 'User ID saved',
      'my_game_id_label': 'My Game ID (for auto-detect)',
      'my_game_id_hint': 'Example: 12345678',
      'my_game_id_helper': 'Used to automatically identify "Me" during import.',
      'history_path_label': 'Game History Folder',
      'history_path_hint': 'Select folder...',
      'dark_mode': 'Dark Theme',
      'light_mode': 'Light Theme',
      'theme_unavailable': 'Light theme is currently unavailable',
      'dev_mode_subtitle': 'Enable advanced features',
      'asset_gallery': 'Asset Gallery',
      'check_icons': 'Check icons',
      'cleanup_players': 'Clean up player database',
      'cleanup_players_desc': 'Delete players who are not in any match',
      'deleted_profiles': 'Deleted profiles: ',
      'version': 'Version',
      'access_method': 'File Access Method',
      'saf_method': 'SAF (System Picker)',
      'saf_desc':
          'Recommended for Android 10, 11 and 12. Access to "data" folder is restricted on Android 13+.',
      'shizuku_method': 'Shizuku (ADB)',
      'shizuku_desc': 'Requires Shizuku app. Full data access.',
      'pick_saf_folder': 'Select SAF Folder',
      'change_saf_folder': 'Change SAF Folder',
      'request_shizuku': 'Request Shizuku Access',
      'current_folder': 'Current folder: ',
      'custom_shizuku_path': 'Custom Shizuku Path',
      'path_saved': 'Path saved',
      'shizuku_granted': 'Shizuku access granted',
      'shizuku_denied': 'Shizuku access denied',
      'shizuku_unavailable': 'Shizuku service not running',
      'shizuku_not_installed': 'Shizuku not installed',
      'import_history': 'Import History',
      'import_success': 'Imported: ',
      'folder_not_selected':
          'Folder not selected.\nGo to Settings -> Select SAF Folder.',
      'no_files_found': 'No files found or access denied.',
      'manual_import_hint': 'Import History (hold for manual)',
      'debug_file_manager': 'Debug File Manager',
      'debug_fm_desc': 'Explore Native & SAF files',
      'saf_hint':
          'Choose com.mobile.legends if from Google Play, or com.mobilelegends.hwag if from AppGallery.',
      'shizuku_hint':
          'Download Shizuku from Play Store or GitHub to use this method.',
      'shizuku_link': 'https://shizuku.rikka.app/download/',
      'match_no_player': 'Match without player',
      'select_history_file': 'Select History File',
      'change_file': 'Change File',
      'parse_failed': 'Failed to parse history file.',
      'save_error': 'Error saving game. Possibly duplicate match ID.',
      'result_label': 'Result: ',
      'date_label': 'Date: ',
      'players_label': 'Players: ',
      'heroes_tab': 'Heroes',
      'items_tab': 'Items',
      'roles_tab': 'Roles',
      'blessings_tab': 'Blessings',
      'spells_tab': 'Spells',
      'id_label': 'ID: ',
      'search_player_label': 'Search by Player Name',
      'no_games_found': 'No games found.',
      'setup_access': 'Setup Access',
      'import_method': 'Import Method',
      'import_method_desc': 'Choose how to access game data.',
      'saf_info_title': 'SAF Instruction',
      'shizuku_info_title': 'Shizuku Instruction',
      'saf_step1': 'Click the button below - the system Files app will open.',
      'saf_step2':
          'Navigate to: Android > data > com.mobile.legends > files > dragon2017 > FightHistory',
      'saf_step2_hw':
          'Note for AppGallery: Android > data > com.mobilelegends.hwag > files > dragon2017 > FightHistory',
      'saf_step3': 'Click the blue "Use this folder" button at the bottom.',
      'shizuku_not_running': 'Shizuku not running',
      'shizuku_step1': 'Install and start the Shizuku service.',
      'shizuku_step2': 'Return here and click "Check Status".',
      'shizuku_step3': 'A system permission request will appear - allow it.',
      'shizuku_download': 'Download Shizuku (shizuku.rikka.app)',
      'shizuku_permission_note':
          'Note: Permission is requested upon checking status, not within the Shizuku app itself.',
      'check_status': 'CHECK STATUS',
      'open_picker': 'OPEN EXPLORER',
      'no_new_games': 'No new games found',
      'access_label': 'Access: ',
      'reset_access_desc': 'Tap to reset access method',
      'shizuku_error_friendly':
          'Failed to connect to Shizuku. Ensure the service is running.',
      'auto_import_title': 'Auto-import Matches',
      'auto_import_desc': 'Automatically search for new games on app resume',
    },
    'ru': {
      'app_title': 'Аналитик MLBB',
      'recent': 'Игры',
      'stats': 'Инфо',
      'search': 'Поиск',
      'add': 'Добавить',
      'settings': 'Настройки',
      'victory': 'ПОБЕДА',
      'defeat': 'ПОРАЖЕНИЕ',
      'my_team': 'МОЯ КОМАНДА',
      'enemy_team': 'ВРАГИ',
      'with_me': 'ЗА МЕНЯ',
      'against_me': 'ПРОТИВ',
      'without_me': 'БЕЗ МЕНЯ',
      'standalone': 'Вне моих игр',
      'hero': 'Герой',
      'nickname': 'Никнейм',
      'kda': 'KDA',
      'gold': 'Золото',
      'items': 'Предметы',
      'score': 'Оценка',
      'duration': 'Время игры',
      'match_date': 'Дата матча',
      'match_time': 'Время матча',
      'save_match': 'СОХРАНИТЬ',
      'scan_screenshot': 'СКАНИРОВАТЬ',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'required': 'Обязательно',
      'invalid': 'Некорректно',
      'match_details': 'Детали матча',
      'no_games': 'Нет сохраненных игр.',
      'delete_game': 'Игра удалена',
      'language': 'Язык',
      'theme': 'Тема',
      'developer_mode': 'Режим разработчика',
      'about': 'О приложении',
      'error': 'Ошибка',
      'ok': 'ОК',
      'search_hint': 'Поиск по нику или герою',
      'role': 'Роль',
      'jungle': 'Лес',
      'roam': 'Роум',
      'mid': 'Мид',
      'gold_lane': 'Золото',
      'exp_lane': 'Опыт',
      'unknown': 'Неизвестно',
      'select_blessing': 'Выберите благословение',
      'none_boots': 'Нет (Обычные сапоги)',
      'physical': 'Физ.',
      'magic': 'Маг.',
      'defense': 'Защита',
      'movement': 'Сапоги',
      'all': 'Все',
      'tier_3': 'Тир 3',
      'tier_all': 'Все тиры',
      'spell': 'Заклинание',
      'select_spell': 'Боевое заклинание',
      'my_nickname': 'Мой никнейм',
      'manage_players': 'Игроки',
      'players_desc': 'Управление никами и комментариями',
      'level': 'Уровень',
      'battle_stats': 'БОЕВАЯ СТАТИСТИКА',
      'damage_hero': 'Урон по героям',
      'damage_tower': 'Урон по башням',
      'damage_taken': 'Полученный урон',
      'heal_label': 'Лечение',
      'kill_part': 'Участие в килах',
      'cc_label': 'Контроль',
      'best_streak': 'Лучшая серия',
      'gold_sources': 'ИСТОЧНИКИ ЗОЛОТА',
      'lane_gold': 'Линия',
      'kill_gold': 'Убийства',
      'jungle_gold': 'Лес',
      'close': 'ЗАКРЫТЬ',
      'alias': 'Алиасы (Ники)',
      'comments': 'Комментарии',
      'add_alias': 'Добавить новый алиас',
      'add_comment_hint': 'Добавить комментарий',
      'unpin': 'Открепить',
      'pin_desc': 'Закрепить (будет основным)',
      'history': 'ИСТОРИЯ ИГР',
      'top_heroes': 'ТОП ГЕРОЕВ',
      'other_heroes': 'ОСТАЛЬНЫЕ ГЕРОИ',
      'games_count': 'Игр:',
      'ally': 'Союзник',
      'enemy': 'Враг',
      'player_profile': 'Профиль игрока',
      'your_profile': 'Ваш профиль',
      'player_settings': 'Настройки игрока',
      'search_stats_coming': 'Статистика скоро появится',
      'search_coming': 'Поиск скоро появится',
      'search_stats_desc': 'Винрейты, любимые герои и многое другое!',
      'search_desc': 'Поиск по игроку, герою или ID матча!',
      'empty': 'Пусто',
      'you_label': 'Это вы',
      'search_nick_hint': 'Поиск по нику...',
      'save_id_success': 'ID пользователя сохранен',
      'my_game_id_label': 'Мой Game ID (для авто-определения)',
      'my_game_id_hint': 'Например: 12345678',
      'my_game_id_helper':
          'Нужен для автоматического определения "Меня" при импорте.',
      'history_path_label': 'Папка с историей игр',
      'history_path_hint': 'Выберите папку...',
      'dark_mode': 'Темная тема',
      'light_mode': 'Светлая тема',
      'theme_unavailable': 'Светлая тема временно недоступна',
      'dev_mode_subtitle': 'Включить расширенные функции',
      'asset_gallery': 'Галерея ассетов',
      'check_icons': 'Просмотр иконок',
      'cleanup_players': 'Очистить базу игроков',
      'cleanup_players_desc': 'Удалить игроков, которых нет ни в одном матче',
      'deleted_profiles': 'Удалено профилей: ',
      'version': 'Версия',
      'access_method': 'Метод доступа к файлам',
      'saf_method': 'SAF (Системный)',
      'saf_desc':
          'Рекомендуется для Android 10, 11 и 12. На Android 13+ доступ к папке "data" заблокирован системой.',
      'shizuku_method': 'Shizuku (ADB)',
      'shizuku_desc': 'Требует Shizuku. Полный доступ к данным.',
      'pick_saf_folder': 'Выбрать папку SAF',
      'change_saf_folder': 'Сменить папку SAF',
      'request_shizuku': 'Запросить права Shizuku',
      'current_folder': 'Текущая папка: ',
      'custom_shizuku_path': 'Кастомный путь Shizuku',
      'path_saved': 'Путь сохранен',
      'shizuku_granted': 'Доступ Shizuku получен',
      'shizuku_denied': 'В доступе Shizuku отказано',
      'shizuku_unavailable': 'Сервис Shizuku не запущен',
      'shizuku_not_installed': 'Shizuku не установлен',
      'import_history': 'Импорт истории',
      'import_success': 'Импортировано: ',
      'folder_not_selected':
          'Папка не выбрана.\nПерейдите в Настройки -> Выбрать папку SAF.',
      'no_files_found': 'Файлы не найдены или нет доступа.',
      'manual_import_hint': 'Импортировать историю (удерж. для выбора файла)',
      'debug_file_manager': 'Debug File Manager',
      'debug_fm_desc': 'Explore Native & SAF files',
      'saf_hint':
          'Выберите com.mobile.legends если игра из Google Play, или com.mobilelegends.hwag если из AppGallery.',
      'shizuku_hint':
          'Скачайте Shizuku из Play Store или GitHub для использования этого метода.',
      'shizuku_link': 'https://shizuku.rikka.app/download/',
      'match_no_player': 'Матч без игрока',
      'select_history_file': 'Выбрать файл истории',
      'change_file': 'Сменить файл',
      'parse_failed': 'Ошибка разбора файла истории.',
      'save_error': 'Ошибка сохранения игры. Возможно, дубликат ID матча.',
      'result_label': 'Результат: ',
      'date_label': 'Дата: ',
      'players_label': 'Игроки: ',
      'heroes_tab': 'Герои',
      'items_tab': 'Предметы',
      'roles_tab': 'Роли',
      'blessings_tab': 'Благословения',
      'spells_tab': 'Заклинания',
      'id_label': 'ID: ',
      'search_player_label': 'Поиск по имени игрока',
      'no_games_found': 'Игры не найдены.',
      'setup_access': 'Настройка доступа',
      'import_method': 'Метод импорта',
      'import_method_desc': 'Выберите способ получения данных.',
      'saf_info_title': 'Инструкция SAF',
      'shizuku_info_title': 'Инструкция Shizuku',
      'saf_step1': 'Нажмите кнопку ниже — откроется системный проводник.',
      'saf_step2':
          'Перейдите по пути: Android > data > com.mobile.legends > files > dragon2017 > FightHistory',
      'saf_step2_hw':
          'Для версии из AppGallery: Android > data > com.mobilelegends.hwag > files > dragon2017 > FightHistory',
      'saf_step3': 'Нажмите кнопку "Использовать эту папку" внизу экрана.',
      'shizuku_not_running': 'Shizuku не запущен',
      'shizuku_step1': 'Установите и запустите сервис Shizuku.',
      'shizuku_step2': 'Вернитесь сюда и нажмите "Проверить статус".',
      'shizuku_step3':
          'После нажатия появится системный запрос на доступ — разрешите его.',
      'shizuku_download': 'Скачать Shizuku (shizuku.rikka.app)',
      'shizuku_permission_note':
          'Примечание: Разрешение запрашивается именно при проверке статуса, а не в самом приложении Shizuku.',
      'check_status': 'ПРОВЕРИТЬ СТАТУС',
      'open_picker': 'ОТКРЫТЬ ПРОВОДНИК',
      'no_new_games': 'Новых игр не найдено',
      'access_label': 'Доступ: ',
      'reset_access_desc': 'Нажмите, чтобы сбросить метод доступа',
      'shizuku_error_friendly':
          'Не удалось связаться с Shizuku. Убедитесь, что сервис запущен.',
      'auto_import_title': 'Авто-импорт матчей',
      'auto_import_desc':
          'Автоматически искать новые игры при входе в приложение',
    },
  };

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return _localizedValues[locale]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }
}
