import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'MLBB Stats',
      'recent': 'Recent',
      'stats': 'Stats',
      'search': 'Search',
      'add': 'Add',
      'settings': 'Settings',
      'victory': 'VICTORY',
      'defeat': 'DEFEAT',
      'my_team': 'MY TEAM',
      'enemy_team': 'ENEMY TEAM',
      'hero': 'Hero',
      'nickname': 'Nickname',
      'kda': 'KDA',
      'gold': 'Gold',
      'items': 'Items',
      'score': 'Score',
      'duration': 'Duration',
      'match_date': 'Match Date',
      'match_time': 'Match Time',
      'save_match': 'SAVE MATCH',
      'scan_screenshot': 'SCAN SCREENSHOT',
      'edit_player': 'Edit Player',
      'edit_my_stats': 'Edit My Stats',
      'cancel': 'Cancel',
      'save': 'Save',
      'required': 'Required',
      'invalid': 'Invalid',
      'match_details': 'Match Details',
      'no_games': 'No games recorded yet.',
      'delete_game': 'Game deleted',
      'language': 'Language',
      'theme': 'Theme',
      'developer_mode': 'Developer Mode',
      'about': 'About',
      'pick_image': 'Pick Image',
      'extracting': 'User stats extracted!',
      'error': 'Error',
      'ok': 'OK',
      'search_hint': 'Search by Player or Hero',
      'role': 'Role',
      'jungle': 'Jungle',
      'roam': 'Roam',
      'mid': 'Mid Lane',
      'gold_lane': 'Gold Lane',
      'exp_lane': 'Exp Lane',
      'unknown': 'Unknown',
      'select_blessing': 'Select Blessing',
      'none_boots': 'None (Normal Boots)',
      'physical': 'Physical',
      'magic': 'Magic',
      'defense': 'Defense',
      'movement': 'Movement',
      'all': 'All',
      'tier_3': 'Tier 3',
      'tier_all': 'All Tiers',
      'spell': 'Spell',
      'select_spell': 'Select Spell',
      'my_nickname': 'My Nickname',
      'manage_players': 'Manage Players',
      'players_desc': 'Merge nicknames and manage friends',
      'calibration': 'Calibration',
      'calibration_desc': 'Setup screenshot parsing zones',
      'calib_step0': 'Select match result screenshot',
      'calib_step1': 'Match Result area',
      'calib_step2': 'Left Team area',
      'calib_step3': 'Right Team area',
      'calib_step4': 'Left: Hero Icon (Circle)',
      'calib_step5': 'Left: Nickname',
      'calib_step6': 'Left: KDA',
      'calib_step7': 'Left: Gold',
      'calib_step8': 'Left: Score',
      'calib_step9': 'Left: Item 1',
      'calib_step10': 'Left: Item 2',
      'calib_step11': 'Left: Item 3',
      'calib_step12': 'Left: Item 4',
      'calib_step13': 'Left: Item 5',
      'calib_step14': 'Left: Item 6',
      'calib_step15': 'Left: Item 7',
      'calib_step16': 'Right: Hero Icon (Circle)',
      'calib_step17': 'Right: Nickname',
      'calib_step18': 'Right: KDA',
      'calib_step19': 'Right: Gold',
      'calib_step20': 'Right: Score',
      'calib_step21': 'Right: Item 1',
      'calib_step22': 'Right: Item 2',
      'calib_step23': 'Right: Item 3',
      'calib_step24': 'Right: Item 4',
      'calib_step25': 'Right: Item 5',
      'calib_step26': 'Right: Item 6',
      'calib_step27': 'Right: Item 7',
      'next': 'Next',
      'finish': 'Finish',
    },
    'ru': {
      'app_title': 'Статистика MLBB',
      'recent': 'Игры',
      'stats': 'Инфо',
      'search': 'Поиск',
      'add': 'Добавить',
      'settings': 'Настройки',
      'victory': 'ПОБЕДА',
      'defeat': 'ПОРАЖЕНИЕ',
      'my_team': 'МОЯ КОМАНДА',
      'enemy_team': 'ВРАГИ',
      'hero': 'Герой',
      'nickname': 'Никнейм',
      'kda': 'KDA',
      'gold': 'Золото',
      'items': 'Предметы',
      'score': 'Оценка',
      'duration': 'Время игры',
      'match_date': 'Дата матча',
      'match_time': 'Время матча',
      'save_match': 'СОХРАНИТЬ',
      'scan_screenshot': 'СКАНИРОВАТЬ',
      'edit_player': 'Игрок',
      'edit_my_stats': 'Моя статистика',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'required': 'Обязательно',
      'invalid': 'Некорректно',
      'match_details': 'Детали матча',
      'no_games': 'Нет сохраненных игр.',
      'delete_game': 'Игра удалена',
      'language': 'Язык',
      'theme': 'Тема',
      'developer_mode': 'Режим разработчика',
      'about': 'О приложении',
      'pick_image': 'Выбрать фото',
      'extracting': 'Статистика извлечена!',
      'error': 'Ошибка',
      'ok': 'ОК',
      'search_hint': 'Поиск по нику или герою',
      'role': 'Роль',
      'jungle': 'Лес',
      'roam': 'Роум',
      'mid': 'Мид',
      'gold_lane': 'Золото',
      'exp_lane': 'Опыт',
      'unknown': 'Неизвестно',
      'select_blessing': 'Выберите благословение',
      'none_boots': 'Нет (Обычные сапоги)',
      'physical': 'Физ.',
      'magic': 'Маг.',
      'defense': 'Защита',
      'movement': 'Сапоги',
      'all': 'Все',
      'tier_3': 'Тир 3',
      'tier_all': 'Все тиры',
      'spell': 'Заклинание',
      'select_spell': 'Боевое заклинание',
      'my_nickname': 'Мой никнейм',
      'manage_players': 'Игроки',
      'players_desc': 'Связывание ников и управление друзьями',
      'calibration': 'Калибровка',
      'calibration_desc': 'Настройка зон сканирования',
      'calib_step0': 'Выберите скриншот результатов',
      'calib_step1': 'Результат (Победа/Поражение)',
      'calib_step2': 'Зона ЛЕВОЙ команды',
      'calib_step3': 'Зона ПРАВОЙ команды',
      'calib_step4': 'ЛЕВО: Иконка героя (КРУГ)',
      'calib_step5': 'ЛЕВО: Никнейм',
      'calib_step6': 'ЛЕВО: KDA',
      'calib_step7': 'ЛЕВО: Золото',
      'calib_step8': 'ЛЕВО: Оценка',
      'calib_step9': 'ЛЕВО: Предмет 1',
      'calib_step10': 'ЛЕВО: Предмет 2',
      'calib_step11': 'ЛЕВО: Предмет 3',
      'calib_step12': 'ЛЕВО: Предмет 4',
      'calib_step13': 'ЛЕВО: Предмет 5',
      'calib_step14': 'ЛЕВО: Предмет 6',
      'calib_step15': 'ЛЕВО: Предмет 7',
      'calib_step16': 'ПРАВО: Иконка героя (КРУГ)',
      'calib_step17': 'ПРАВО: Никнейм',
      'calib_step18': 'ПРАВО: KDA',
      'calib_step19': 'ПРАВО: Золото',
      'calib_step20': 'ПРАВО: Оценка',
      'calib_step21': 'ПРАВО: Предмет 1',
      'calib_step22': 'ПРАВО: Предмет 2',
      'calib_step23': 'ПРАВО: Предмет 3',
      'calib_step24': 'ПРАВО: Предмет 4',
      'calib_step25': 'ПРАВО: Предмет 5',
      'calib_step26': 'ПРАВО: Предмет 6',
      'calib_step27': 'ПРАВО: Предмет 7',
      'next': 'Далее',
      'finish': 'Завершить',
    },
  };

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return _localizedValues[locale]?[key] ?? _localizedValues['en']![key] ?? key;
  }
}