import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'MLBB Analyst',
      'recent': 'Recent',
      'stats': 'Stats',
      'search': 'Search',
      'add': 'Add',
      'settings': 'Settings',
      'victory': 'VICTORY',
      'defeat': 'DEFEAT',
      'my_team': 'MY TEAM',
      'enemy_team': 'ENEMY TEAM',
      'with_me': 'WITH ME',
      'against_me': 'AGAINST ME',
      'hero': 'Hero',
      'nickname': 'Nickname',
      'kda': 'KDA',
      'gold': 'Gold',
      'items': 'Items',
      'score': 'Score',
      'duration': 'Duration',
      'match_date': 'Match Date',
      'match_time': 'Match Time',
      'save_match': 'SAVE MATCH',
      'scan_screenshot': 'SCAN SCREENSHOT',
      'cancel': 'Cancel',
      'save': 'Save',
      'required': 'Required',
      'invalid': 'Invalid',
      'match_details': 'Match Details',
      'no_games': 'No games recorded yet.',
      'delete_game': 'Game deleted',
      'language': 'Language',
      'theme': 'Theme',
      'developer_mode': 'Developer Mode',
      'about': 'About',
      'error': 'Error',
      'ok': 'OK',
      'search_hint': 'Search by Player or Hero',
      'role': 'Role',
      'jungle': 'Jungle',
      'roam': 'Roam',
      'mid': 'Mid Lane',
      'gold_lane': 'Gold Lane',
      'exp_lane': 'Exp Lane',
      'unknown': 'Unknown',
      'select_blessing': 'Select Blessing',
      'none_boots': 'None (Normal Boots)',
      'physical': 'Physical',
      'magic': 'Magic',
      'defense': 'Defense',
      'movement': 'Movement',
      'all': 'All',
      'tier_3': 'Tier 3',
      'tier_all': 'All Tiers',
      'spell': 'Spell',
      'select_spell': 'Select Spell',
      'my_nickname': 'My Nickname',
      'manage_players': 'Players',
      'players_desc': 'Manage nicknames and comments',
      'calibration': 'Calibration',
      'calibration_desc': 'Setup screenshot parsing zones',
      'level': 'Level',
      'battle_stats': 'BATTLE STATS',
      'damage_hero': 'Damage to Heroes',
      'damage_tower': 'Damage to Towers',
      'damage_taken': 'Damage Taken',
      'heal_label': 'Healing',
      'kill_part': 'Kill Participation',
      'cc_label': 'Control',
      'best_streak': 'Best Streak',
      'gold_sources': 'GOLD SOURCES',
      'lane_gold': 'Lane',
      'kill_gold': 'Kills',
      'jungle_gold': 'Jungle',
      'close': 'CLOSE',
      'alias': 'Aliases (Nicknames)',
      'comments': 'Comments',
      'add_alias': 'Add new alias',
      'add_comment_hint': 'Add comment',
      'unpin': 'Unpin',
      'pin_desc': 'Pin (will be main)',
      'history': 'GAME HISTORY',
      'top_heroes': 'TOP HEROES',
      'other_heroes': 'OTHER HEROES',
      'games_count': 'Games:',
      'ally': 'Ally',
      'enemy': 'Enemy',
      'player_profile': 'Player Profile',
      'your_profile': 'Your Profile',
      'player_settings': 'Player Settings',
      'search_stats_coming': 'Statistics Coming Soon',
      'search_coming': 'Search Coming Soon',
      'search_stats_desc': 'Win rates, favorite heroes, and more!',
      'search_desc': 'Search by player, hero, or match ID!',
      'empty': 'Empty',
      'you_label': 'It\'s you',
      'search_nick_hint': 'Search by nickname...',
      'save_id_success': 'User ID saved',
      'my_game_id_label': 'My Game ID (for auto-detect)',
      'my_game_id_hint': 'Example: 12345678',
      'my_game_id_helper': 'Used to automatically identify "Me" during import.',
      'history_path_label': 'Game History Folder',
      'history_path_hint': 'Select folder...', 
      'dark_mode': 'Dark Theme',
      'light_mode': 'Light Theme',
      'theme_unavailable': 'Light theme is currently unavailable',
      'dev_mode_subtitle': 'Enable advanced features',
      'asset_gallery': 'Asset Gallery',
      'check_icons': 'Check icons',
      'cleanup_players': 'Clean up player database',
      'cleanup_players_desc': 'Delete players who are not in any match',
      'deleted_profiles': 'Deleted profiles: ',
      'version': 'Version',
    },
    'ru': {
      'app_title': 'Аналитик MLBB',
      'recent': 'Игры',
      'stats': 'Инфо',
      'search': 'Поиск',
      'add': 'Добавить',
      'settings': 'Настройки',
      'victory': 'ПОБЕДА',
      'defeat': 'ПОРАЖЕНИЕ',
      'my_team': 'МОЯ КОМАНДА',
      'enemy_team': 'ВРАГИ',
      'with_me': 'ЗА МЕНЯ',
      'against_me': 'ПРОТИВ',
      'hero': 'Герой',
      'nickname': 'Никнейм',
      'kda': 'KDA',
      'gold': 'Золото',
      'items': 'Предметы',
      'score': 'Оценка',
      'duration': 'Время игры',
      'match_date': 'Дата матча',
      'match_time': 'Время матча',
      'save_match': 'СОХРАНИТЬ',
      'scan_screenshot': 'СКАНИРОВАТЬ',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'required': 'Обязательно',
      'invalid': 'Некорректно',
      'match_details': 'Детали матча',
      'no_games': 'Нет сохраненных игр.',
      'delete_game': 'Игра удалена',
      'language': 'Язык',
      'theme': 'Тема',
      'developer_mode': 'Режим разработчика',
      'about': 'О приложении',
      'error': 'Ошибка',
      'ok': 'ОК',
      'search_hint': 'Поиск по нику или герою',
      'role': 'Роль',
      'jungle': 'Лес',
      'roam': 'Роум',
      'mid': 'Мид',
      'gold_lane': 'Золото',
      'exp_lane': 'Опыт',
      'unknown': 'Неизвестно',
      'select_blessing': 'Выберите благословение',
      'none_boots': 'Нет (Обычные сапоги)',
      'physical': 'Физ.',
      'magic': 'Маг.',
      'defense': 'Защита',
      'movement': 'Сапоги',
      'all': 'Все',
      'tier_3': 'Тир 3',
      'tier_all': 'Все тиры',
      'spell': 'Заклинание',
      'select_spell': 'Боевое заклинание',
      'my_nickname': 'Мой никнейм',
      'manage_players': 'Игроки',
      'players_desc': 'Управление никами и комментариями',
      'calibration': 'Калибровка',
      'calibration_desc': 'Настройка зон сканирования',
      'level': 'Уровень',
      'battle_stats': 'БОЕВАЯ СТАТИСТИКА',
      'damage_hero': 'Урон по героям',
      'damage_tower': 'Урон по башням',
      'damage_taken': 'Полученный урон',
      'heal_label': 'Лечение',
      'kill_part': 'Участие в килах',
      'cc_label': 'Контроль',
      'best_streak': 'Лучшая серия',
      'gold_sources': 'ИСТОЧНИКИ ЗОЛОТА',
      'lane_gold': 'Линия',
      'kill_gold': 'Убийства',
      'jungle_gold': 'Лес',
      'close': 'ЗАКРЫТЬ',
      'alias': 'Алиасы (Ники)',
      'comments': 'Комментарии',
      'add_alias': 'Добавить новый алиас',
      'add_comment_hint': 'Добавить комментарий',
      'unpin': 'Открепить',
      'pin_desc': 'Закрепить (будет основным)',
      'history': 'ИСТОРИЯ ИГР',
      'top_heroes': 'ТОП ГЕРОЕВ',
      'other_heroes': 'ОСТАЛЬНЫЕ ГЕРОИ',
      'games_count': 'Игр:',
      'ally': 'Союзник',
      'enemy': 'Враг',
      'player_profile': 'Профиль игрока',
      'your_profile': 'Ваш профиль',
      'player_settings': 'Настройки игрока',
      'search_stats_coming': 'Статистика скоро появится',
      'search_coming': 'Поиск скоро появится',
      'search_stats_desc': 'Винрейты, любимые герои и многое другое!',
      'search_desc': 'Поиск по игроку, герою или ID матча!',
      'empty': 'Пусто',
      'you_label': 'Это вы',
      'search_nick_hint': 'Поиск по нику...', 
      'save_id_success': 'ID пользователя сохранен',
      'my_game_id_label': 'Мой Game ID (для авто-определения)',
      'my_game_id_hint': 'Например: 12345678',
      'my_game_id_helper': 'Нужен для автоматического определения "Меня" при импорте.',
      'history_path_label': 'Папка с историей игр',
      'history_path_hint': 'Выберите папку...', 
      'dark_mode': 'Темная тема',
      'light_mode': 'Светлая тема',
      'theme_unavailable': 'Светлая тема временно недоступна',
      'dev_mode_subtitle': 'Включить расширенные функции',
      'asset_gallery': 'Галерея ассетов',
      'check_icons': 'Просмотр иконок',
      'cleanup_players': 'Очистить базу игроков',
      'cleanup_players_desc': 'Удалить игроков, которых нет ни в одном матче',
      'deleted_profiles': 'Удалено профилей: ',
      'version': 'Версия',
    }
  };

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    return _localizedValues[locale]?[key] ?? _localizedValues['en']![key] ?? key;
  }
}