class GameEntity {
  final String id;
  final String en;
  final String ru;
  final String category; // 'physical', 'magic', 'defense', 'movement'
  final int tier; // 1, 2, 3

  const GameEntity({
    required this.id, 
    required this.en, 
    required this.ru, 
    this.category = 'hero',
    this.tier = 3,
  });
}

class GameData {
  // --- HEROES (Preserved 131 + 2) ---
  static const List<GameEntity> heroes = [
    // 2016
    GameEntity(id: 'miya', en: 'Miya', ru: 'Мия'),
    GameEntity(id: 'balmond', en: 'Balmond', ru: 'Бальмонд'),
    GameEntity(id: 'saber', en: 'Saber', ru: 'Сабер'),
    GameEntity(id: 'alice', en: 'Alice', ru: 'Алиса'),
    GameEntity(id: 'nana', en: 'Nana', ru: 'Нана'),
    GameEntity(id: 'tigreal', en: 'Tigreal', ru: 'Тигрил'),
    GameEntity(id: 'alucard', en: 'Alucard', ru: 'Алукард'),
    GameEntity(id: 'karina', en: 'Karina', ru: 'Карина'),
    GameEntity(id: 'akai', en: 'Akai', ru: 'Акай'),
    GameEntity(id: 'franco', en: 'Franco', ru: 'Франко'),
    GameEntity(id: 'bane', en: 'Bane', ru: 'Бейн'),
    GameEntity(id: 'bruno', en: 'Bruno', ru: 'Бруно'),
    GameEntity(id: 'clint', en: 'Clint', ru: 'Клинт'),
    GameEntity(id: 'rafaela', en: 'Rafaela', ru: 'Рафаэль'),
    GameEntity(id: 'eudora', en: 'Eudora', ru: 'Эйдора'),
    GameEntity(id: 'zilong', en: 'Zilong', ru: 'Зилонг'),
    GameEntity(id: 'fanny', en: 'Fanny', ru: 'Фанни'),
    GameEntity(id: 'layla', en: 'Layla', ru: 'Лейла'),
    GameEntity(id: 'minotaur', en: 'Minotaur', ru: 'Минотавр'),
    GameEntity(id: 'lolita', en: 'Lolita', ru: 'Лолита'),
    GameEntity(id: 'hayabusa', en: 'Hayabusa', ru: 'Хаябуса'),
    GameEntity(id: 'freya', en: 'Freya', ru: 'Фрейя'),
    GameEntity(id: 'gord', en: 'Gord', ru: 'Горд'),
    GameEntity(id: 'natalia', en: 'Natalia', ru: 'Наталья'),
    GameEntity(id: 'kagura', en: 'Kagura', ru: 'Кагура'),
    GameEntity(id: 'chou', en: 'Chou', ru: 'Чу'),
    GameEntity(id: 'sun', en: 'Sun', ru: 'Сан'),
    GameEntity(id: 'alpha', en: 'Alpha', ru: 'Альфа'),
    GameEntity(id: 'ruby', en: 'Ruby', ru: 'Руби'),
    // 2017
    GameEntity(id: 'yi_sun_shin', en: 'Yi Sun-shin', ru: 'Ли Сун-Син'),
    GameEntity(id: 'moskov', en: 'Moskov', ru: 'Москов'),
    GameEntity(id: 'johnson', en: 'Johnson', ru: 'Джонсон'),
    GameEntity(id: 'cyclops', en: 'Cyclops', ru: 'Циклоп'),
    GameEntity(id: 'estes', en: 'Estes', ru: 'Эстес'),
    GameEntity(id: 'hilda', en: 'Hilda', ru: 'Хильда'),
    GameEntity(id: 'aurora', en: 'Aurora', ru: 'Аврора'),
    GameEntity(id: 'lapu_lapu', en: 'Lapu-Lapu', ru: 'Лапу-Лапу'),
    GameEntity(id: 'vexana', en: 'Vexana', ru: 'Вексана'),
    GameEntity(id: 'roger', en: 'Roger', ru: 'Роджер'),
    GameEntity(id: 'karrie', en: 'Karrie', ru: 'Кэрри'),
    GameEntity(id: 'gatotkaca', en: 'Gatotkaca', ru: 'Гатоткача'),
    GameEntity(id: 'harley', en: 'Harley', ru: 'Харли'),
    GameEntity(id: 'irithel', en: 'Irithel', ru: 'Иритель'),
    GameEntity(id: 'grock', en: 'Grock', ru: 'Грок'),
    GameEntity(id: 'argus', en: 'Argus', ru: 'Аргус'),
    GameEntity(id: 'odette', en: 'Odette', ru: 'Одетта'),
    GameEntity(id: 'lancelot', en: 'Lancelot', ru: 'Ланселот'),
    GameEntity(id: 'diggie', en: 'Diggie', ru: 'Дигги'),
    GameEntity(id: 'hylos', en: 'Hylos', ru: 'Хилос'),
    GameEntity(id: 'zhask', en: 'Zhask', ru: 'Заск'),
    GameEntity(id: 'helcurt', en: 'Helcurt', ru: 'Хелкарт'),
    GameEntity(id: 'pharsa', en: 'Pharsa', ru: 'Фарса'),
    // 2018
    GameEntity(id: 'lesley', en: 'Lesley', ru: 'Лесли'),
    GameEntity(id: 'jawhead', en: 'Jawhead', ru: 'Кусака'),
    GameEntity(id: 'angela', en: 'Angela', ru: 'Ангела'),
    GameEntity(id: 'gusion', en: 'Gusion', ru: 'Госсен'),
    GameEntity(id: 'valir', en: 'Valir', ru: 'Валир'),
    GameEntity(id: 'martis', en: 'Martis', ru: 'Мартис'),
    GameEntity(id: 'uranus', en: 'Uranus', ru: 'Уранус'),
    GameEntity(id: 'hanabi', en: 'Hanabi', ru: 'Ханаби'),
    GameEntity(id: 'change', en: 'Chang\'e', ru: 'Чан\'Э'),
    GameEntity(id: 'kaja', en: 'Kaja', ru: 'Кайя'),
    GameEntity(id: 'selena', en: 'Selena', ru: 'Селена'),
    GameEntity(id: 'aldous', en: 'Aldous', ru: 'Алдос'),
    GameEntity(id: 'claude', en: 'Claude', ru: 'Клауд'),
    GameEntity(id: 'vale', en: 'Vale', ru: 'Вейл'),
    GameEntity(id: 'leomord', en: 'Leomord', ru: 'Леоморд'),
    GameEntity(id: 'lunox', en: 'Lunox', ru: 'Люнокс'),
    GameEntity(id: 'hanzo', en: 'Hanzo', ru: 'Ханзо'),
    GameEntity(id: 'belerick', en: 'Belerick', ru: 'Белерик'),
    GameEntity(id: 'kimmy', en: 'Kimmy', ru: 'Кимми'),
    GameEntity(id: 'thamuz', en: 'Thamuz', ru: 'Тамуз'),
    GameEntity(id: 'harith', en: 'Harith', ru: 'Харит'),
    GameEntity(id: 'minsitthar', en: 'Minsitthar', ru: 'Минситтар'),
    GameEntity(id: 'kadita', en: 'Kadita', ru: 'Кадита'),
    // 2019
    GameEntity(id: 'badang', en: 'Badang', ru: 'Баданг'),
    GameEntity(id: 'khufra', en: 'Khufra', ru: 'Хуфра'),
    GameEntity(id: 'faramis', en: 'Faramis', ru: 'Фарамис'),
    GameEntity(id: 'granger', en: 'Granger', ru: 'Грейнджер'),
    GameEntity(id: 'guinevere', en: 'Guinevere', ru: 'Гвиневра'),
    GameEntity(id: 'esmeralda', en: 'Esmeralda', ru: 'Эсмеральда'),
    GameEntity(id: 'terizla', en: 'Terizla', ru: 'Теризла'),
    GameEntity(id: 'xborg', en: 'X.Borg', ru: 'Икс.Борг'),
    GameEntity(id: 'dyrroth', en: 'Dyrroth', ru: 'Дайрот'),
    GameEntity(id: 'lylia', en: 'Lylia', ru: 'Лилия'),
    GameEntity(id: 'baxia', en: 'Baxia', ru: 'Баксий'),
    GameEntity(id: 'masha', en: 'Masha', ru: 'Маша'),
    GameEntity(id: 'wanwan', en: 'Wanwan', ru: 'Ванван'),
    GameEntity(id: 'silvanna', en: 'Silvanna', ru: 'Сильвана'),
    GameEntity(id: 'ling', en: 'Ling', ru: 'Линг'),
    // 2020
    GameEntity(id: 'cecilion', en: 'Cecilion', ru: 'Сесилион'),
    GameEntity(id: 'carmilla', en: 'Carmilla', ru: 'Кармилла'),
    GameEntity(id: 'atlas', en: 'Atlas', ru: 'Атлас'),
    GameEntity(id: 'popol_kupa', en: 'Popol and Kupa', ru: 'Пополь и Купа'),
    GameEntity(id: 'yu_zhong', en: 'Yu Zhong', ru: 'Ю Чонг'),
    GameEntity(id: 'luo_yi', en: 'Luo Yi', ru: 'Ло Йи'),
    GameEntity(id: 'khaleed', en: 'Khaleed', ru: 'Халид'),
    GameEntity(id: 'barats', en: 'Barats', ru: 'Баратс'),
    GameEntity(id: 'brody', en: 'Brody', ru: 'Броуди'),
    GameEntity(id: 'benedetta', en: 'Benedetta', ru: 'Бенедетта'),
    GameEntity(id: 'mathilda', en: 'Mathilda', ru: 'Матильда'),
    // 2021
    GameEntity(id: 'paquito', en: 'Paquito', ru: 'Пакито'),
    GameEntity(id: 'beatrix', en: 'Beatrix', ru: 'Беатрис'),
    GameEntity(id: 'phoveus', en: 'Phoveus', ru: 'Фовиус'),
    GameEntity(id: 'gloo', en: 'Gloo', ru: 'Глу'),
    GameEntity(id: 'yve', en: 'Yve', ru: 'Ив'),
    GameEntity(id: 'natan', en: 'Natan', ru: 'Натан'),
    GameEntity(id: 'aulus', en: 'Aulus', ru: 'Аулус'),
    GameEntity(id: 'aamon', en: 'Aamon', ru: 'Эймон'),
    GameEntity(id: 'valentina', en: 'Valentina', ru: 'Валентина'),
    GameEntity(id: 'edith', en: 'Edith', ru: 'Эдит'),
    GameEntity(id: 'floryn', en: 'Floryn', ru: 'Флорин'),
    // 2022
    GameEntity(id: 'yin', en: 'Yin', ru: 'Инь'),
    GameEntity(id: 'melissa', en: 'Melissa', ru: 'Мелисса'),
    GameEntity(id: 'xavier', en: 'Xavier', ru: 'Ксавьер'),
    GameEntity(id: 'julian', en: 'Julian', ru: 'Джулиан'),
    GameEntity(id: 'fredrinn', en: 'Fredrinn', ru: 'Фредрин'),
    GameEntity(id: 'joy', en: 'Joy', ru: 'Джой'),
    // 2023
    GameEntity(id: 'arlott', en: 'Arlott', ru: 'Арлотт'),
    GameEntity(id: 'novaria', en: 'Novaria', ru: 'Новария'),
    GameEntity(id: 'ixia', en: 'Ixia', ru: 'Иксия'),
    GameEntity(id: 'nolan', en: 'Nolan', ru: 'Нолан'),
    GameEntity(id: 'cici', en: 'Cici', ru: 'Чичи'),
    // 2024+
    GameEntity(id: 'chip', en: 'Chip', ru: 'Чип'),
    GameEntity(id: 'zhuxin', en: 'Zhuxin', ru: 'Чжу Синь'),
    GameEntity(id: 'suyou', en: 'Suyou', ru: 'Су Е'),
    GameEntity(id: 'lukas', en: 'Lukas', ru: 'Лукас'),
    GameEntity(id: 'kalea', en: 'Kalea', ru: 'Калеа'),
    // Special
    GameEntity(id: 'zetian', en: 'Zetian', ru: 'Зетиан'),
    GameEntity(id: 'sora', en: 'Sora', ru: 'Сора'),
    GameEntity(id: 'obsidia', en: 'Obsidia', ru: 'Обсидия'),
  ];
  
  // --- BLESSINGS (Boot Modifiers) ---
  static const List<GameEntity> blessings = [
     // Jungle
     GameEntity(id: 'flame_retribution', en: 'Flame Retribution', ru: 'Пламенное Возмездие', category: 'jungle'),
     GameEntity(id: 'ice_retribution', en: 'Ice Retribution', ru: 'Ледяное Возмездие', category: 'jungle'),
     GameEntity(id: 'bloody_retribution', en: 'Bloody Retribution', ru: 'Кровавое Возмездие', category: 'jungle'),
     // Roam
     GameEntity(id: 'conceal', en: 'Conceal', ru: 'Маскировка', category: 'roam'),
     GameEntity(id: 'encourage', en: 'Encourage', ru: 'Поощрение', category: 'roam'),
     GameEntity(id: 'favor', en: 'Favor', ru: 'Благосклонность', category: 'roam'),
     GameEntity(id: 'dire_hit', en: 'Dire Hit', ru: 'Острый Удар', category: 'roam'),
  ];

  // --- ITEMS (Ordered by Shop Category) ---
  static const List<GameEntity> items = [
    // === PHYSICAL ===
    GameEntity(id: 'dagger', en: 'Dagger', ru: 'Кинжал', category: 'physical', tier: 1),
    GameEntity(id: 'knife', en: 'Knife', ru: 'Нож', category: 'physical', tier: 1),
    GameEntity(id: 'vampire_mallet', en: 'Vampire Mallet', ru: 'Вампирская Колотушка', category: 'physical', tier: 2),
    GameEntity(id: 'javelin', en: 'Javelin', ru: 'Копье', category: 'physical', tier: 1),
    GameEntity(id: 'iron_hunting_bow', en: 'Iron Hunting Bow', ru: 'Железный Охотничий Лук', category: 'physical', tier: 2), 
    GameEntity(id: 'ogre_tomahawk', en: 'Ogre Tomahawk', ru: 'Томагавк Огра', category: 'physical', tier: 2),
    GameEntity(id: 'legion_sword', en: 'Legion Sword', ru: 'Меч Легиона', category: 'physical', tier: 2),
    GameEntity(id: 'swift_crossbow', en: 'Swift Crossbow', ru: 'Арбалет Охотника', category: 'physical', tier: 2), 
    GameEntity(id: 'regular_spear', en: 'Regular Spear', ru: 'Обычное Копье', category: 'physical', tier: 2),
    GameEntity(id: 'fury_hammer', en: 'Fury Hammer', ru: 'Молот Гнева', category: 'physical', tier: 2),
    GameEntity(id: 'rogue_meteor', en: 'Rogue Meteor', ru: 'Метеор Бродяги', category: 'physical', tier: 2),

    GameEntity(id: 'sea_halberd', en: 'Sea Halberd', ru: 'Трезубец', category: 'physical'),
    GameEntity(id: 'rose_gold_meteor', en: 'Rose Gold Meteor', ru: 'Золотой Метеор', category: 'physical'),
    GameEntity(id: 'hunter_strike', en: 'Hunter Strike', ru: 'Удар Охотника', category: 'physical'),
    GameEntity(id: 'blade_of_despair', en: 'Blade of Despair', ru: 'Клинок Отчаяния', category: 'physical'),
    GameEntity(id: 'blade_of_heptaseas', en: 'Blade of the Heptaseas', ru: 'Клинок Семи Морей', category: 'physical'),
    GameEntity(id: 'wind_of_nature', en: 'Wind of Nature', ru: 'Ветер Природы', category: 'physical'),
    GameEntity(id: 'malefic_roar', en: 'Malefic Roar', ru: 'Злобный Рык', category: 'physical'),
    GameEntity(id: 'berserkers_fury', en: 'Berserker\'s Fury', ru: 'Ярость Берсерка', category: 'physical'),
    GameEntity(id: 'endless_battle', en: 'Endless Battle', ru: 'Бесконечная Битва', category: 'physical'),
    GameEntity(id: 'windtalker', en: 'Windtalker', ru: 'Говорящий с Ветром', category: 'physical'),
    GameEntity(id: 'haass_claws', en: 'Haas\'s Claws', ru: 'Когти Хааса', category: 'physical'),
    GameEntity(id: 'corrosion_scythe', en: 'Corrosion Scythe', ru: 'Коса Коррозии', category: 'physical'),
    GameEntity(id: 'demon_hunter_sword', en: 'Demon Hunter Sword', ru: 'Меч Охотника на Демонов', category: 'physical'),
    GameEntity(id: 'golden_staff', en: 'Golden Staff', ru: 'Золотой Посох', category: 'physical'),
    GameEntity(id: 'war_axe', en: 'War Axe', ru: 'Топор Войны', category: 'physical'),
    GameEntity(id: 'great_dragon_spear', en: 'Great Dragon Spear', ru: 'Копье Великого Дракона', category: 'physical'),
    GameEntity(id: 'sky_piercer', en: 'Sky Piercer', ru: 'Небесный Пронзатель', category: 'physical'),
    GameEntity(id: 'malefic_gun', en: 'Malefic Gun', ru: 'Злобный Пистолет', category: 'physical'),

    // === MAGIC ===
    GameEntity(id: 'magic_wand', en: 'Magic Wand', ru: 'Магическая Палочка', category: 'magic', tier: 2),
    GameEntity(id: 'mystery_codex', en: 'Mystery Codex', ru: 'Книга Тайн', category: 'magic', tier: 1),
    GameEntity(id: 'power_crystal', en: 'Power Crystal', ru: 'Кристалл Силы', category: 'magic', tier: 1), 
    GameEntity(id: 'magic_blade', en: 'Magic Blade', ru: 'Магический Клинок', category: 'magic', tier: 2),
    GameEntity(id: 'book_of_sages', en: 'Book of Sages', ru: 'Книга Мудрецов', category: 'magic', tier: 2),
    GameEntity(id: 'exotic_veil', en: 'Exotic Veil', ru: 'Вуаль Странника', category: 'magic', tier: 2),
    GameEntity(id: 'elegant_gem', en: 'Elegant Gem', ru: 'Элегантный Самоцвет', category: 'magic', tier: 2),
    GameEntity(id: 'tome_of_evil', en: 'Tome of Evil', ru: 'Книга Зла', category: 'magic', tier: 2),
    GameEntity(id: 'azure_blade', en: 'Azure Blade', ru: 'Лазурный Клинок', category: 'magic', tier: 2),

    GameEntity(id: 'genius_wand', en: 'Genius Wand', ru: 'Палочка Гения', category: 'magic'),
    GameEntity(id: 'lightning_truncheon', en: 'Lightning Truncheon', ru: 'Жезл Молний', category: 'magic'),
    GameEntity(id: 'fleeting_time', en: 'Fleeting Time', ru: 'Мимолетное Время', category: 'magic'),
    GameEntity(id: 'blood_wings', en: 'Blood Wings', ru: 'Кровавые Крылья', category: 'magic'),
    GameEntity(id: 'clock_of_destiny', en: 'Clock of Destiny', ru: 'Часы Судьбы', category: 'magic'),
    GameEntity(id: 'starlium_scythe', en: 'Starlium Scythe', ru: 'Коса Звезд', category: 'magic'),
    GameEntity(id: 'glowing_wand', en: 'Glowing Wand', ru: 'Пылающий Жезл', category: 'magic'),
    GameEntity(id: 'ice_queen_wand', en: 'Ice Queen Wand', ru: 'Жезл Снежной Королевы', category: 'magic'),
    GameEntity(id: 'concentrated_energy', en: 'Concentrated Energy', ru: 'Концентрированная Энергия', category: 'magic'),
    GameEntity(id: 'holy_crystal', en: 'Holy Crystal', ru: 'Священный Кристалл', category: 'magic'),
    GameEntity(id: 'divine_glaive', en: 'Divine Glaive', ru: 'Божественный Меч', category: 'magic'),
    GameEntity(id: 'winter_crown', en: 'Winter Crown', ru: 'Зимняя Корона', category: 'magic'), 
    GameEntity(id: 'enchanted_talisman', en: 'Enchanted Talisman', ru: 'Зачарованный Талисман', category: 'magic'),
    GameEntity(id: 'feather_of_heaven', en: 'Feather of Heaven', ru: 'Райское Перо', category: 'magic'),
    GameEntity(id: 'wishing_lantern', en: 'Wishing Lantern', ru: 'Фонарь Желаний', category: 'magic'),
    GameEntity(id: 'flask_of_the_oasis', en: 'Flask of the Oasis', ru: 'Фляга Оазиса', category: 'magic'),

    // === DEFENSE ===
    GameEntity(id: 'leather_jerkin', en: 'Leather Jerkin', ru: 'Кожаная Куртка', category: 'defense', tier: 1),
    GameEntity(id: 'magic_resist_cloak', en: 'Magic Resist Cloak', ru: 'Плащ Магической Защиты', category: 'defense', tier: 1),
    GameEntity(id: 'vitality_crystal', en: 'Vitality Crystal', ru: 'Кристалл Живучести', category: 'defense', tier: 1),
    GameEntity(id: 'ares_belt', en: 'Ares Belt', ru: 'Пояс Ареса', category: 'defense', tier: 2),
    GameEntity(id: 'molten_essence', en: 'Molten Essence', ru: 'Расплавленная Эссенция', category: 'defense', tier: 2),
    GameEntity(id: 'black_ice_shield', en: 'Black Ice Shield', ru: 'Щит Черного Льда', category: 'defense', tier: 2),
    GameEntity(id: 'dreadnaught_armor', en: 'Dreadnaught Armor', ru: 'Броня Устрашения', category: 'defense', tier: 2),
    GameEntity(id: 'silence_robe', en: 'Silence Robe', ru: 'Мантия Тишины', category: 'defense', tier: 2),
    GameEntity(id: 'steel_legplates', en: 'Steel Legplates', ru: 'Стальные Поножи', category: 'defense', tier: 2),
    GameEntity(id: 'heros_ring', en: 'Hero\'s Ring', ru: 'Кольцо Героя', category: 'defense', tier: 2),

    GameEntity(id: 'chastise_pauldron', en: 'Chastise Pauldron', ru: 'Плащ Наказания', category: 'defense', tier: 3),
    GameEntity(id: 'radiant_armor', en: 'Radiant Armor', ru: 'Сияющая Броня', category: 'defense'),     GameEntity(id: 'twilight_armor', en: 'Twilight Armor', ru: 'Сумеречная Броня', category: 'defense'),
    GameEntity(id: 'brute_force_breastplate', en: 'Brute Force Breastplate', ru: 'Кираса Грубой Силы', category: 'defense'),
    GameEntity(id: 'immortality', en: 'Immortality', ru: 'Бессмертие', category: 'defense'),
    GameEntity(id: 'dominance_ice', en: 'Dominance Ice', ru: 'Господство Льда', category: 'defense'),
    GameEntity(id: 'athenas_shield', en: 'Athena\'s Shield', ru: 'Щит Афины', category: 'defense'),
    GameEntity(id: 'oracle', en: 'Oracle', ru: 'Оракул', category: 'defense'),
    GameEntity(id: 'antique_cuirass', en: 'Antique Cuirass', ru: 'Древняя Кираса', category: 'defense'),
    GameEntity(id: 'guardian_helmet', en: 'Guardian Helmet', ru: 'Шлем Небесного Стража', category: 'defense'),
    GameEntity(id: 'cursed_helmet', en: 'Cursed Helmet', ru: 'Проклятый Шлем', category: 'defense'),
    GameEntity(id: 'thunder_belt', en: 'Thunder Belt', ru: 'Громовой Пояс', category: 'defense'),
    GameEntity(id: 'queens_wings', en: 'Queen\'s Wings', ru: 'Крылья Королевы', category: 'defense'),
    GameEntity(id: 'blade_armor', en: 'Blade Armor', ru: 'Шипованная Броня', category: 'defense'),

    // === MOVEMENT ===
    GameEntity(id: 'boots', en: 'Boots', ru: 'Сапоги', category: 'movement', tier: 1),
    GameEntity(id: 'warrior_boots', en: 'Warrior Boots', ru: 'Сапоги Воина', category: 'movement'),
    GameEntity(id: 'tough_boots', en: 'Tough Boots', ru: 'Прочные Сапоги', category: 'movement'),
    GameEntity(id: 'magic_shoes', en: 'Magic Shoes', ru: 'Магические Сапоги', category: 'movement'),
    GameEntity(id: 'arcane_boots', en: 'Arcane Boots', ru: 'Сапоги Заклинателя', category: 'movement'),
    GameEntity(id: 'swift_boots', en: 'Swift Boots', ru: 'Сапоги Спешки', category: 'movement'),
    GameEntity(id: 'demon_shoes', en: 'Demon Shoes', ru: 'Обувь Демона', category: 'movement'),
    GameEntity(id: 'rapid_boots', en: 'Rapid Boots', ru: 'Сапоги-Скороходы', category: 'movement', tier: 3),

    // === OTHER ===
    GameEntity(id: 'lantern_of_hope', en: 'Lantern of Hope', ru: 'Фонарь Надежды', category: 'other'),
    GameEntity(id: 'flower_of_hope', en: 'Flower of Hope', ru: 'Цветок Надежды', category: 'other'),
  ];

  static const List<GameEntity> spells = [
    GameEntity(id: 'execute', en: 'Execute', ru: 'Кара'),
    GameEntity(id: 'retribution', en: 'Retribution', ru: 'Возмездие'),
    GameEntity(id: 'inspire', en: 'Inspire', ru: 'Вдохновение'),
    GameEntity(id: 'sprint', en: 'Sprint', ru: 'Спринт'),
    GameEntity(id: 'revitalize', en: 'Revitalize', ru: 'Исцеление'),
    GameEntity(id: 'aegis', en: 'Aegis', ru: 'Щит'),
    GameEntity(id: 'petrify', en: 'Petrify', ru: 'Оцепенение'),
    GameEntity(id: 'purify', en: 'Purify', ru: 'Очищение'),
    GameEntity(id: 'flameshot', en: 'Flameshot', ru: 'Огненный выстрел'),
    GameEntity(id: 'flicker', en: 'Flicker', ru: 'Вспышка'),
    GameEntity(id: 'arrival', en: 'Arrival', ru: 'Прибытие'),
    GameEntity(id: 'vengeance', en: 'Vengeance', ru: 'Отомщение'),
  ];
}
